### PR TITLE
Added JSON properties for 'BasePageConfig', 'SettingBounds' and 'EditableLobbySettings'

### PR DESCRIPTION
**Pull request by BigETI**
This pull request adds JSON properties for 'BasePageConfig', 'SettingBounds' and 'EditableLobbySettings'.

### CODE REVIEW

**Comment by BigETI** [comment]
I don't know why my latest commit fails on `Test_getRandomWords` in `./game/words_test.go`.

**Comment by Bios-Marcel** [comment]
Renamings in HTML files are missing

**Comment by Bios-Marcel** [comment]
Oh and the tests fail ^^

**Comment by Bios-Marcel** [comment]
I think the test failure was just unlucky, cause I wrote a test that has a 1% chance to randomly fail.

**Pull request merged**
