### PR TITLE
'agoraclass'

### PR DESCRIPTION
**Pull request by feixiangdjames**
web video support / I created a new folder that is named [assets]

### CODE REVIEW

**Comment by feixiangdjames** [comment]
update video-box style

**Comment by Bios-Marcel** [comment]
Yo, please don't make PRs on master ;)

**Comment by feixiangdjames** [comment]
ok, sorry about that

**Comment by Bios-Marcel** [comment]
Hey, I just checked out the code and I don't really understand how to use this. It's not really integrated into the app, right? Either way, I am not sure whether this is in the scope of a simple drawing game. As it is right now, I will not merge it. Feel free to elaborate further on it though.

**Pull request closed without merging**
