### PR TITLE
[Please ignore this] Deployment fix on Heroku. Closes #2

### LINKED ISSUE #2: Public lobbies
The player should be able to make his lobby public, allowing other players to join a random lobby.

### PR DESCRIPTION
**Pull request by marcomicera**

### CODE REVIEW

**Comment by marcomicera** [comment]
Sorry, I created this PR by mistake, you can delete it.

**Comment by Bios-Marcel** [comment]
If you need the port stuff, we can allow setting it via both the command parameters and the environment variables

**Comment by marcomicera** [comment]
Nah don't worry, I don't wanna waste any of your time. I'm just translating this game so I can play it with my friends while being on lockdown. Thanks anyway!

**Comment by Bios-Marcel** [comment]
Tbh, it'd be cool if people could just spin up a temporary instance to play on via herokus free-tier. Especially if my VPS goes down, I die, decide to not pay for my VPS anymore or whatever. So, if you are done with this, I'd appreciate a PR :D

**Comment by marcomicera** [comment]
Sure! I'm not really practical with Golang, but as soon as I manage to make it an option I'll make a PR!

**Pull request closed without merging**
