### PR TITLE
Fix #249 touch input on computers

### LINKED ISSUE #249: Drawing with touch does not work on a computer with touchscreen
Drawing on the canvas using the touch screen of a Windows computer does not work. It appears as though `isDrawing` variable is never changed to _true_.

It seems that [_ontouchstart_, _ontouchmove_, _ontouchend_](https://github.com/scribble-rs/scribble.rs/blob/5d25414b670ecb09793cac75ab95a78a7674c946/communication/templates/lobby.html#L1191-L1244) never trigger.

I was able to fix the problem by introducing two new functions for _touchstart_ and _touchmove_ similar to `onTouchEnd(e)` and then adding the following attributes directly to the canvas element (in HTML): `ontouchstart="onTouchStart(event)" ontouchmove="onTouchMove(event)" ontouchend="onTouchEnd(event)"`

Tested on Windows 10 in both Firefox 86.0.1 and Chrome 88.0.4324.190

### PR DESCRIPTION
**Pull request by zznidar**
This fixed touch input on a Windows computer for me. Fixes #249

### CODE REVIEW

**Comment by Bios-Marcel** [comment]
ontouchstart/end already exist. Now the code is duplicated. It seems that the way to register them causes problems.

Either way, I'd prefer we register all events in a consistent manner. Afaik addEventListener(....) seems to be the most stable variant of doing this.

However, I'd love to find out WHY this doesn't work as it is now. It works perfectly fine on android.

**Comment by zznidar** [comment]
You're right. I have now deduplicated it, making it similar to how onTouchEnd had already been there.

**Comment by Bios-Marcel** [comment]
Now this for example, breaks touch simulation mode for me.

**Comment by Bios-Marcel** [comment]
This however works:

```html
<canvas id="drawing-board"></canvas>
```

```js
    drawingBoard.addEventListener('touchend', onTouchEnd);
    drawingBoard.addEventListener('touchcancel', onTouchEnd);
    drawingBoard.addEventListener('touchstart', onTouchStart);
    drawingBoard.addEventListener('touchmove', onTouchMove);
```

I tested this with firefox touch simulation and android firefox.

**Comment by zznidar** [comment]
I was afraid something like this would happen. Thanks for the addEventListener suggestion -- I have tried it and it works for me in Firefox and Chrome on Windows.

**Comment by Bios-Marcel** [comment]
So, the thing that surprises me still, is why this happens at all. Look at how we register mouse listeners. Haven't heard anyone complain about those.

**Comment by zznidar** [comment]
It seems that .ontouchmove, .ontouchstart, .ontouchend, .ontouchcancel event handlers are not implemented in desktop browsers: https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/ontouchmove#browser_compatibility

However, adding touch events as addEventListener is supported in most browsers both on desktop and on mobile: https://caniuse.com/touch

**Comment by Bios-Marcel** [comment]
Oh, I see. So the touch simulation mode also simulates the mobile APIs. Meaning that it works in the same browser that normally doesn't support it. Hm, interesting.

**Comment by Bios-Marcel** [comment]
Thanks :)

**Pull request merged**
