### PR TITLE
Add german wordlist

### PR DESCRIPTION
**Pull request by kaiffeetasse**
Added a simple german wordlist and a "German" option in languages

### CODE REVIEW

**Comment by Bios-Marcel** [comment]
I think it'd be good to just translate the english list, because it has quite a lot of words compared to this one.

**Comment by Bios-Marcel** [comment]
The english list was translated into italian by a script I think. Am i right in that assumption @Luni-4 ? If so, would you mind sharing the script?

**Comment by Luni-4** [comment]
> The english list was translated into italian by a script I think. Am i right in that assumption @Luni-4 ? If so, would you mind sharing the script?

I've removed all the {e,m,h,i} tags at the end of the word, then I uploaded the untagged text file on an online automatic translator. Eventually I've re-added the tags using a Python script.

**Comment by thielepaul** [comment]
> I think it'd be good to just translate the english list, because it has quite a lot of words compared to this one.

I just translated it with Google Translate:
[words_de.txt](https://github.com/scribble-rs/scribble.rs/files/4398072/words_de.txt)

**Comment by lryjnks** [comment]
+1 & please update the docker container too.

**Comment by Bios-Marcel** [comment]
Those autoupdate

**Pull request merged**
