### PR TITLE
Add support for public lobbies

### PR DESCRIPTION
**Pull request by Bios-Marcel**
This commit is quite huge I admit. I redesigned the home-page, since a new UI component for joining a public lobby was necessary. Since I had some layout problems, I changed a lot fo the CSS and HTML as well. It's still not perfect, as the table has a "fixed" size, since it keeps ignoring `max-height`.

Anyway, relevant stuff:

* Lobbies can now be made public (Default: private)
* Homepage now has a tab-component
  * Next to "Create Lobby", there's now "Join Lobby" as a tab
* `/v1/lobby` now accepts GET and other HTTP method types. For get it returns all lobbies, for everything else it creates a lobby.

### CODE REVIEW

**Comment by Bios-Marcel** [comment]
Hey @SZenglein would you mind reviewing this PR. I'd like someone to look and this and test this. I'd be thankful if you'd do that :)

**Comment by SZenglein** [comment]
I'd be happy to. Unfortunately I can't build the project since you added packr and the makefile.

**Comment by Bios-Marcel** [comment]
Why?

**Comment by SZenglein** [comment]
I'll create an issue real quick.

**Comment by SZenglein** [comment]
So I am quite busy right now. I'll try looking at it tomorrow, but can't promise anything.

**Comment by Bios-Marcel** [comment]
no stress mate :)

**Comment by SZenglein** [comment]
First thing I noticed: The footer is obscured by the drawing controls. Is this intentional? It's good that the controls are now always visible, but this does look strange
grafik

**Comment by Bios-Marcel** [comment]
fml

**Comment by SZenglein** [comment]
I noticed resizing only occurs when changing the window width. So the canvas should also be resized when changing the height to prevent it from becoming larger than the page and forcing scrolling. I think this is a relatively easy fix, and should be included in the rumoured canvas rewrite.

**Comment by SZenglein** [comment]
I looked at the code and tested a few things by hand. So far, everything is looking fine.

* Maximum number of IPs is working as expected with reverse proxy
* Creating and joining public (and private) lobbies works
* Gameplay working as expected

As far as I can tell from my limited go knowledge, looks fine. Lots of renames and formatting bloating the diff, so does appear to be larger than it is.

**Comment by Bios-Marcel** [comment]
Yeah, i was lazy, i did the renames for a reason, but then decided i do it a different way. Should've reverted those.

**Comment by Bios-Marcel** [comment]
Manually merging this, cause i fucked up.

**Pull request closed without merging**
