### PR TITLE
Feature/add french translations

### PR DESCRIPTION
**Pull request by piteur**
Hi there!

Thanks for this open-source project.
I found it after the "original" website was buggy and decided to contribute with French translations to let my friends play it :)

I also added a bash script to translate words, with few notes:
 - it's not optimized
 - I used AWS api calls instead of Google Translate (seen references in project issues previously)
 - I renamed the files, as we already have a `words` subfolder it made more sense to me

_Notes:_
not quite sure what the usage of `word#[i|h|X]` pattern in the word file, so I got rid of it, like on another translation file. Code is not explicit and did not find any explanation.
I will happily update the documentation :)

Cheers!

### CODE REVIEW

**Comment by Bios-Marcel** [comment]
Uhm, those were my guesses of how difficult words were to draw. `#i` meant impossible :sweat_smile:

**Comment by piteur** [comment]
@Bios-Marcel - AHAH, good to know then. French people will suffer and break friendship with this translation file then :D 

I will rework it a bit then and add documentation!
By any chance do you have a list for the difficulty levels?

**Comment by Bios-Marcel** [comment]
Honestly, I am planning on removing the difficulty stuff. I meant to rework the whole word-set concept. I don't know when I'll get to it though. Currently there's still some other problems with layout and device compatibility. I am not much of a webdev, so I am kind of struggling here. Anyway, see: https://github.com/scribble-rs/scribble.rs/issues/84

**Comment by piteur** [comment]
Gotcha, I'm a backend/SRE so frontend is definitely not my thing as well!

From a player point of view, having sometime shitty/harder words make the game better: more challenging and struggle to draw/guess make it less linear. But that's up to individuals!

I will not rework the file then, and let it like that.
Let me know if you need any changes to this MR!

**Comment by Bios-Marcel** [comment]
Btw, what's so buggy about skribbl.io recently?

**Comment by Bios-Marcel** [comment]
Uhm, could you by any chance remove the word that were previously labeled #i, I guess this would make a lot of people frustrated. The ones labeled with #h are already pretty hard ^^

**Comment by HeadFox** [comment]
Working perfectly but french is missing in game/lobby.go !
L37
```go
SupportedLanguages = map[string]string{
		"english": "English",
		"italian": "Italian",
		"german":  "German",
	}
```

**Comment by piteur** [comment]
Updated :)

**Comment by piteur** [comment]
I may have found a bug 🤔 
I set the game parameter to be in French, and the words "lean" and "mainstrean" are not part of the `resources/words/fr` file.
I will investigate a bit later, but just FYI.

Screenshot 2020-04-08 at 19 47 02

**Comment by kiwy42** [comment]
I have no idea how to help with commit and pull request I am not really working a lot with git in general.
However regarding the automated translation have some issue. IMHO words should never be at the plural form, and special character such as `œ` should be simplified in `oe` for example as absolutly no one knows how to type it with a regular azerty keyboard.
I've done a similar job here https://pastebin.com/QMVfxpLp  (still with tag but it's certainly not the hardest part to get rid off)
I don't know if it helps but I hope so.
Anyway, I'm glad to see such enthusiasm and work on this game. It's great to have in those time.
Have a nice day.

**Comment by Bios-Marcel** [comment]
Yeah, the plural thing is a problem in the languages as well.

Regarding the bug, I'll look into it over the next days and merge the PR if it's unrelated

**Comment by piteur** [comment]
Hey @kiwy42 - thanks :)

> However regarding the automated translation have some issue. IMHO words should never be at the plural form, and special character such as œ should be simplified in oe for example as absolutly no one knows how to type it with a regular azerty keyboard.

I'm planning a new MR as well to fix that, as `eo` should be acceoted for `œ`. It's a nice to have feature, and avoid any frustration.
For the plural, I must admit I don't want to edit the translations line per line to find the plural and fix it. It may be automated later, with a dedicated more powerful API than AWS.

> Regarding the bug, I'll look into it over the next days and merge the PR if it's unrelated

I believe it's unrelated to the MR, as the changes are minor ones. Up to you! :)

**Comment by Bios-Marcel** [comment]
Yeah, the code shouldn't cause such a bug ^^

**Comment by Bios-Marcel** [comment]
How do you reproduce this bug? Might the form have submitted something incorrect?

**Comment by piteur** [comment]
Thanks for the merge 🎉 

> How do you reproduce this bug? Might the form have submitted something incorrect?

I want to investigate more, as it happens randomly.
No clear reproduction path for now on my side.

**Pull request merged**
