### PR TITLE
Touch

### PR DESCRIPTION
**Pull request by SZenglein**
The existing touch implementation had some problems. It was really lagging hard with the manual line-drawing implementation. It also didn't follow the allowDrawing flag, so you could freely draw even when not allowed. 
It should now work on more platforms and integrate better.

I also improved the drawing performance by using built in functions and removing the existing implementation, which was really slow.

### CODE REVIEW

**Comment by Bios-Marcel** [comment]
there's a good reason for the custom drawing algorithm.

**Comment by SZenglein** [comment]
That makes sense, however, the performance is absolutely horrible. Do you have any plans/ideas to make it better?

**Comment by Bios-Marcel** [comment]
i'll look into it today

**Comment by SZenglein** [comment]
I just realized I reverted some changes you made in cdb4a70eb30ec69a37af6b10462af4268282aace . I want to add that "ontouchstart" and those functions do not work for me. Since the original code also did it my way, maybe it should be kept that way.

Would you agree to the touch changes if I revert the drawing stuff?

**Comment by Bios-Marcel** [comment]
Weird, it worked for me. Whqt browser are you on

**Comment by SZenglein** [comment]
It works on Android, apart from being able to draw before a word is chosen. On a Windows 10 Laptop touch events are only registered when using addEventListener. 

It is also a bit buggy when using touch and accidentally moving the mouse. I admit it is an edge case but just using extra touch coordinates solves it nicely.

**Comment by Bios-Marcel** [comment]
I'll be waiting with this PR for one or two days. As I am doing a huge refactoring right now. Don't worry though, I'll resolve conflicts later on :)

**Comment by Bios-Marcel** [comment]
With these changes, touch doesn't work for me in simulated mode.

**Comment by SZenglein** [comment]
Well, it works on real hardware and did not before. I could even test it on an iPad by now.

Does it really matter if you set the callback via addEventListener?

**Comment by Bios-Marcel** [comment]
Apparently the e.preventdefault is needed.

**Comment by SZenglein** [comment]
That didn't do anything for me. What is it supposed to do?

**Comment by SZenglein** [comment]
I think the preventDefault prevents a touch event from scrolling on the canvas, but I solved this with CSS.

**Comment by SZenglein** [comment]
I can confirm this touch code works on Firefox Android, Chrome Android, Windows 10 Edge, Windows 10 Firefox and Safari on iPad. 

Maybe someone else can also test it, but I would prefer real touch devices over simulated touch.

**Comment by Bios-Marcel** [comment]
I'll be trying to handle as many cases as possible. I am looking into it. I'll be giving you a patch. Maybe you can test that with your touchdevice. Gimme some mins :)

**Comment by Bios-Marcel** [comment]
No matter how I do it, there's always a broken thing. Sometimes it actually seems to end up deadlocking and I am not sure why. This might be a bug in the drawing algorithm tho :man_shrugging: 

Since I can't test this on any actual touch device, I am not gonna touch this for now. This is pretty much something impossible to test for me, as the browser tools in both chrome and firefox are not working very well in general ... which suprises me. Maybe it's a linux thing. However, I am gonna apply the "isDrawing" check in ontouchmove.

**Comment by SZenglein** [comment]
Have you tried registering the functions with both methods? I can try if that works maybe tomorrow. The registering is basically the only thing I changed.

**Comment by Bios-Marcel** [comment]
Maybe i should try giving my phone access to port 8080 of my PC, then i could probably try testing properly. but i cba to do that right now as i have no clue how it works ^^

**Comment by SZenglein** [comment]
You mentioned you're on Linux, right? You can just disable your firewall (or do it properly and open the port).

**Comment by Bios-Marcel** [comment]
I'll just be replacing all calls with "addEventListener"

**Pull request closed without merging**
