### PR TITLE
Allow selecting your own words at the selection screen

### PR DESCRIPTION
**Pull request by L-as**
This feature needs to be enabled manually at the lobby
creation menu.
You still get 3 words in the same way before (for inspiration),
but you in addition have an extra text input field and a button
for submitting it that allows you to select a custom string.

### CODE REVIEW

**Comment by Bios-Marcel** [comment]
This feature kind of goes against the idea of the game, which is being forced to draw a certain word. Being able to choose completly custom words every turn would kind of destroy that and potentially allow using words that give you a higher chance of earning points quickly.

**Comment by L-as** [comment]
I realize that, but it works fine if you're not playing for points but rather just entertainment with friends.

**Comment by Bios-Marcel** [comment]
Then why not put a custom wordlist in the lobby. I don't think this feature is worth having and maintaining. I also plan to add word galleries later-on. Pre-defined packs and custom public packs. There'll be enough ways to personalize the word choices in a fair way. Please create issues in the future if you plan to introduce gameplay changes, then we can discuss it beforehand.

**Comment by L-as** [comment]
Ah I just implemented it for personal use and thought it might be useful for others too, so no worries.

**Pull request closed without merging**
