### PR TITLE
Making votekick an option in the lobby setup page

### PR DESCRIPTION
**Pull request by hija**
Hey there,

I tried implementing an option to disable Votekicking. I realized that the incentive to kick the other player if you are only two players is too high ;)

**This pull request adds a checkbox "Enable Votekicking" in the lobby creation form. If players try to kick a player although it was disabled in the settings, the kick request is discarded.**

I think, we should also hide the votekick button if votekicking is disabled. I tried to do that with
```

            {{if .EnableVotekick}}
              <button class="kick-button" id="kick-button" type="button" title="Vote to kick this player" alt="Vote to kick this player" onclick="onClickKickButton({{.ID}})">👋</button>
            {{end}}
```

in lobby_players.html, but that broke the lobby. Any help regarding this is appreciated.

I hope I can contribute to this project with this small pull request :)

### CODE REVIEW

**Comment by Bios-Marcel** [comment]
What exactly is the problem with hiding the button? I just tested it and it seems to work just fine.

**Comment by Bios-Marcel** [comment]
You can pass data when the template is executed:

```go
templatingError := lobbyPage.ExecuteTemplate(w, "players", lobby.Players)
```

**Comment by hija** [comment]
I see. That must have been the error. I will try to fix this. Thank you for the hint :)

**Comment by hija** [comment]
@Bios-Marcel, I think instead we should pass the lobby object then - am I right? Otherwise every player would need a "kickable" attribute and I think that would be an overhead. Is there a way to chat with you? I am pretty new to golang and a bit struggeling 😞

**Comment by Bios-Marcel** [comment]
hmu on discord Marcel#5587 or we can use gitter: https://gitter.im/Bios-Marcel/Lobby

**Comment by hija** [comment]
Okay, ich habe es geschafft :)
Jetzt sollte es funktionieren

**Pull request merged**
