### PR TITLE
Added info about the players name and the ability to directly change this for new users

### PR DESCRIPTION
**Pull request by BBJake**
New users often had problems to see their actual name and to find the button change it.
So I added this to the dialog where the round hasn't started...

### CODE REVIEW

**Comment by Bios-Marcel** [comment]
Hey, sorry for not replying earlier.
While this is a good idea, I think the lobbyowner should have the same option.
Maybe we could even make it a textfield with a "confirm" button next to it, instead of opening another dialog.

**Comment by Bios-Marcel** [comment]
Hey, so I actually needed this feature fully implemented on short notice, so I did this myself, sorry ^^

https://github.com/scribble-rs/scribble.rs/commit/94c17c45cf7818c81a0adcca7d2ec43d165c7eb0

Feel free to check it out and give feedback.

**Comment by BBJake** [comment]
No problem. I was busy this week with my main work so I had not time to look for this.
I mainly saw the problem for players, as the lobbyowner most of the time knows what he is doing ;-)
But I think that actually there's a problem with the design. The buttons and the input field nearly look the same, so it is difficult to understand what you have to do in the dialogs...
Additional there is a bug in the "change name" dialog. The input field is not set to the actual name and the randomize button sets only the name in player list. Not in the input field...

**Comment by Bios-Marcel** [comment]
I fixed that bug already, thanks anyways. Regarding the design, any tips?

**Comment by BBJake** [comment]
Maybe some space between the input field and the buttons...
I would also remove the "random"-Button, because I think it doesn't make much sense. The users should set their own name so that they can be better identified...

**Comment by Bios-Marcel** [comment]
Can you create follwoup issues?

**Pull request closed without merging**
