### PR TITLE
#208 - Add option for seperate English(gb) language

### PR DESCRIPTION
**Pull request by maquis196**

### CODE REVIEW

**Comment by Bios-Marcel** [comment]
what's the proper nouns thing? Doesn't seem to exist.

**Comment by maquis196** [comment]
> what's the proper nouns thing? Doesn't seem to exist.

No true, I noticed that a good chunk of the words not in the british dictionary were actually proper nouns. I think long term maybe a separate file with "People" in them would solve a lot of the problems, but abandoned that idea during the work.

**Comment by Bios-Marcel** [comment]
Well, the words generally need a bit more sophistication. I've not done any sorting, grouping and whatnot so far. However, that's just because I am a lazy bum ;D

**Comment by Bios-Marcel** [comment]
Either way, isn't your PR still missing stuff?

For example, this has remained unchanged:

```go
	SupportedLanguages = map[string]string{
		"english": "English",
		"italian": "Italian",
		"german":  "German",
		"french":  "French",
		"dutch":   "Dutch",
	}
```

**Comment by maquis196** [comment]
Ah good catch thanks

**Comment by maquis196** [comment]
Ill reset + squash all my commits too before its ready

**Comment by Bios-Marcel** [comment]
Dw, i can squash too. However, I'd prefer it if you'd use the formatter, so we don't produce unnecessary changes on follow-up commits from other contributors. `gofmt -w -s` is what you are looking for I guess.

**Comment by Bios-Marcel** [comment]
Dutch is the default now. That kinda sucks :D

Let's make `en_US` the default.

**Comment by maquis196** [comment]
> Dutch is the default now. That kinda sucks :D
> 
> Let's make `en_US` the default. Defaulting was already a thing before, I think you broke it by accident.

Interesting, how did I make Dutch default? I added GB to the top of the map, happy swapping gb + us around, but dutch?

**Comment by Bios-Marcel** [comment]
It'd also be nice to still have the API key `english` to default to `en_US`. I'd like to preserve backwards compatibility in this specific case.

**Comment by Bios-Marcel** [comment]
> > Dutch is the default now. That kinda sucks :D
> > Let's make `en_US` the default. Defaulting was already a thing before, I think you broke it by accident.
> 
> Interesting, how did I make Dutch default? I added GB to the top of the map, happy swapping gb + us around, but dutch?

I think the order doesn't matter.

This piece in `lobby_create.html` selected a default:

```go
{{if eq $k $language}}selected="selected"{{end}}
```
it's the `Language` field in the lobby data.

**Comment by Bios-Marcel** [comment]
return &CreatePageData{
		SettingBounds:          game.LobbySettingBounds,
		Languages:              game.SupportedLanguages,
		Public:                 "false",
		DrawingTime:            "120",
		Rounds:                 "4",
		MaxPlayers:             "12",
		CustomWordsChance:      "50",
		ClientsPerIPLimit:      "1",
		EnableVotekick:         "true",
		Language:               "english", <------------
		CurrentlyActiveLobbies: state.GetActiveLobbyCount(),
	}

**Comment by Bios-Marcel** [comment]
I'll look at this again tomorrow I guess. Have a good one.

**Comment by maquis196** [comment]
Sweet, thanks for the tips!

**Comment by Bios-Marcel** [comment]
Everything seems to be working fine, however, I was wondering whether it's intentional that the en_GB dict has 3 words less. I was wondering whether there'll be bigger discrepancies in the future and whether it's worth documenting them?

**Comment by maquis196** [comment]
Yeah some words we just dont have equivalents for or ive never seen/heard used here (so arguably could just leave them in there, since people probably wouldn't pick them, but i know there might be some future higher scoring things)

The words from memory were;

neighbourhood
crawl space

Ah 3 words not 3 lines, i think it was only those two lines overall. Could put them back in to keep the word count identical?

**Comment by Bios-Marcel** [comment]
brits don't use neighbourhood? ^^

**Comment by maquis196** [comment]
> brits don't use neighbourhood? ^^

The word exists obviously, but we dont use it, like we'd say "i was in the area" or "i was in town". I'm happy putting that one back in since obviously any english speaker would understand it. 

Crawl space however, 100% no, we simply dont have that space between the ground and the floor, basements or nothing :)

**Comment by Bios-Marcel** [comment]
Makes sense, thanks for clarifying ;)

**Pull request merged**
