### PR TITLE
Added 'skin' tones to predefined colors

### LINKED ISSUE #236: Predefined colors shold contain "skin" tones
Personally I think it often looks very weird to draw people in orange or pitch black, therefore having the most common skin tones would be quite handy. These colors will be additions to existing ones. You can still draw Donald Trump with his "natural" orange skin tone ;)

### PR DESCRIPTION
**Pull request by Tijmen34**
Added six skin tones to the predefined colors.

Based on [this skin tones palette](https://www.color-hex.com/color-palette/547) and [this softer skin tones palette](https://applecolors.com/palette/1748-soft-skin-palette).

Closes #236

### CODE REVIEW

**Comment by Bios-Marcel** [comment]
I think I'd rather have only 2 or 4 more colors. Especially since I am planning to add the to the API as well, so third party clients can opt into having the same colors. Screen space is also something to think about. Especially for the mobile client.

**Comment by Tijmen34** [comment]
Alright, which color palette would you prefer in that case? Or two colors from each palette?

**Comment by Bios-Marcel** [comment]
So, to be honest. I don't think the colors need to be accurate. Maybe it's enough to have one brown-ish and one white-ish tone that could be real black and white skin colors. Just so that the meaning of the color choice is conveyed and people know what it stands for.

**Comment by Bios-Marcel** [comment]
I kinda already committed this by accident a while ago ^^'

**Pull request closed without merging**
